WTF_CSRF_ENABLED = False
WTF_CSRF_SECRET_KEY = 'tp)xP9D0ArWdtQJXkHPQAB0B22a(6E'
SECRET_KEY = 'tp)xP9D0ArWdtQJXkHPQAB0B22a(6E'
SQLALCHEMY_DATABASE_URI = 'sqlite:///database/energia.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
